"""The brand images shipped as package data, and the loader that finds them.

These guard the packaging seam rather than any logic: the assets are generated by
`make icon` from `design/`, and the way they go missing is a build or package-data
mistake, not a code change.
"""

from __future__ import annotations

from noveltrans.gui.icons import load_pixmap


class TestAppIcon:
    def test_it_loads(self, qapp):
        assert not load_pixmap("app-icon.png").isNull()

    def test_it_is_square(self, qapp):
        pixmap = load_pixmap("app-icon.png")
        assert pixmap.width() == pixmap.height()

    def test_its_corners_are_transparent(self, qapp):
        # design/logo-icon.png has a checkerboard painted into its pixels and a fully
        # opaque alpha channel; make_icon.py crops the tile out and re-masks it. An
        # opaque corner here means that step regressed and the checkerboard shipped.
        image = load_pixmap("app-icon.png").toImage()
        last = image.width() - 1
        for x, y in ((0, 0), (last, 0), (0, last), (last, last)):
            assert image.pixelColor(x, y).alpha() == 0


class TestMissingAsset:
    def test_it_returns_a_null_pixmap(self, qapp):
        assert load_pixmap("no-such-asset.png").isNull()
